### ISSUE TITLE
Offer Item Shows "Mark as Completed" Button When Task Has Been Completed

### ISSUE THREAD

**Issue by ettienekorayyi** [codesydney/migram-frontend#36] opened 2022-07-31 01:14 UTC
Description:
When the user logged as test_provider clicks the "marks as completed" button 4 times, it throws an internal server error. 
Maybe we can disable the button while it's being process in the backend and if the job is completed

- In my opinion, when the user clicks the "marks as completed" button, it should either show a loading spinner so that the user knows its currently processing the request. ***
- If the state of the job is completed, I think the "marks as completed" button should be disabled since it's already completed.

Steps:
1. Log in as customer and post a job
2. Log in as provider and send some offers
3. Accept the offer
4. Click the mark as complete button

Screenshot:
![image](https://user-images.githubusercontent.com/19362078/182005390-e1747d48-13c4-4c59-b459-b7bf6c65a12a.png)

Notes from Dave:
*** - This has been broken out into a separate issue.
**** - Looks like this issue has been doubled up. Related: #22  #30

- [ ] #42

**Comment by engramar** [comment] 2022-08-17 10:02
Thanks @ettienekorayyi , Managed to replicate the issue from my side. I can also see that the 'completed' tag is somewhat like not working at all. 
![image](https://user-images.githubusercontent.com/7553347/185092310-eca2f1b9-d6d9-4f2e-b692-d0fd7d3b1d18.png)

**Comment by davidtaing** [comment] 2022-08-17 15:57
I was able to replicate this one with Postman. It's probably a backend issue, but I need to look into this one more.

![image](https://user-images.githubusercontent.com/8443215/185184552-402d6eba-c01c-466e-832c-c2b7c8061cf9.png)

Interestingly, I ran a GET /tasks/:taskId request in Postman as well and the task is structured in the following way (irrelevant information removed). Note that the "completion" state is being stored in the Task and not in the offer,

```js
{
  status: "success",
  task: {
    status: "completed"
    acceptedOffer: {
      status: "accepted"
    }
  }
}
```

Here, we grab the offers and setState to the offers only. Note that we don't save the parent task, so we don't know if a task has been completed yet.


https://github.com/codesydney/migram-frontend/blob/425b52baaed59508692aa57d91eb6e4b3d06023c/components/offers/Offers.tsx#L23-L27

**Comment by davidtaing** [comment] 2022-08-19 02:47
After having a discussion with Praveen, I was completely wrong about the backend. It is working as intended when you call the `PATCH /tasks/:taskId/complete" endpoint when a task has been completed. I definitely tunnel-visioned on this one.

The problem is actually that the Offer item shows a "Mark as Complete" button when the parent Task is completed. I have renamed the issue.

@ettienekorayyi, with regards to your first comment about the loading spinner, I will break this out into a seperate Github Issue.

**Comment by davidtaing** [comment] 2022-08-19 03:22
Closing this issue for now, as this is a duplicate of #22. Also related #30.

**Closed by davidtaing** 2022-08-19 03:22 UTC
Labels: bug, enhancement, Pre-Soft Launch
